#!/usr/bin/python
import os
import sys
import shutil

def convert_ln_to_file(linkname, dryrun=False):
    try:
        filename = os.readlink(linkname)
        print("found link to:", filename)
    except: 
        print("not a link:", linkname)
        return

    if not dryrun: 
        os.remove(linkname)
        shutil.copyfile(filename, linkname)
        print("created file", linkname)
    else:
        print("not doing anything because dryrun flag is set") 

if __name__ == "__main__":
    import argparse
    import glob

    root_dir = os.path.abspath(os.path.dirname(__file__))

    parser = argparse.ArgumentParser(prog="Symbolik Link Converter", description="Convert symbolik links to the files that they point to.")
    parser.add_argument("path", nargs='+')
    parser.add_argument("-d", "--dryrun", action="store_true")

    args = parser.parse_args()
    for rel_file in args.path:
        linkname = os.path.join(root_dir, rel_file)
        convert_ln_to_file(linkname, dryrun=args.dryrun)
